server:
  port: 3777
spring:  profiles:    active:    - local  devtools:    restart:      enabled: true
---
spring:  profiles:  - local  kafka:    producer:      bootstrap-servers:      - localhost:9092,localhost:9093,localhost:9094       key-serializer:        org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer:        org.apache.kafka.common.serialization.StringSerializer
    admin:      properties:        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094    template:      default-topic: library-event        